os: Visual Studio 2019

branches:
  only:
    - master

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - powershell .\build.ps1 -Target Test